export const assets = {
  // Common icons
  add_icon: "/assets/add_icon.svg",
  arrow_icon: "/assets/arrow_icon.svg",
  arrow_icon_white: "/assets/arrow_icon_white.svg",
  arrow_right_icon_colored: "/assets/arrow_right_icon_colored.svg",
  bose_headphone_image: "/assets/bose_headphone_image.png",
  header_headphone_image: "/assets/header_headphone_image.png",
  header_macbook_image: "/assets/header_macbook_image.png",
  header_playstation_image: "/assets/header_playstation_image.png",
  macbook_image: "/assets/macbook_image.png",
  md_controller_image: "/assets/md_controller_image.png",
  samsung_s23phone_image: "/assets/samsung_s23phone_image.png",

  // Category images
  All_Beauty_image: "/assets/All_Beauty.png",
  Appliances_image: "/assets/Appliances.png",
  Arts_Crafts_and_Sewing_image: "/assets/Arts_Crafts_and_Sewing.png",
  Automotive_image: "/assets/Automotive.jpg",
  Baby_Products_image: "/assets/Baby_Products.jpg",
  Beauty_and_Personal_Care_image: "/assets/Beauty_and_Personal_Care.png",
  Books_image: "/assets/Books.png",
  CDs_and_Vinyl_image: "/assets/CDs_and_Vinyl.png",
  Cell_Phones_and_Accessories_image: "/assets/Cell_Phones_and_Accessories.png",
  Clothing_Shoes_and_Jewelry_image: "/assets/Clothing_Shoes_and_Jewelry.png",
  Digital_Music_image: "/assets/Digital_Music.png",
  Electronics_image: "/assets/Electronics.png",
  Gift_Cards_image: "/assets/Gift_Cards.png",
  Grocery_and_Gourmet_Food_image: "/assets/Grocery_and_Gourmet_Food.png",
  Handmade_Products_image: "/assets/Handmade_Products.png",
  Health_and_Household_image: "/assets/Health_and_Household.png",
  Health_and_Personal_Care_image: "/assets/Health_and_Personal_Care.png",
  Home_and_Kitchen_image: "/assets/Home_and_Kitchen.png",
  Industrial_and_Scientific_image: "/assets/Industrial_and_Scientific.png",
  Kindle_Store_image: "/assets/Kindle_Store.png",
  Magazine_Subscriptions_image: "/assets/Magazine_Subscriptions.png",
  Movies_and_TV_image: "/assets/Movies_and_TV.png",
  Musical_Instruments_image: "/assets/Musical_Instruments.png",
  Office_Products_image: "/assets/Office_Products.png",
  Patio_Lawn_and_Garden_image: "/assets/Patio_Lawn_and_Garden.png",
  Pet_Supplies_image: "/assets/Pet_Supplies.png",
  Software_image: "/assets/Software.png",
  Sports_and_Outdoors_image: "/assets/Sports_and_Outdoors.png",
  Subscription_Boxes_image: "/assets/Subscription_Boxes.png",
  Tools_and_Home_Improvement_image: "/assets/Tools_and_Home_Improvement.png",
  Toys_and_Games_image: "/assets/Toys_and_Games.png",
  Video_Games_image: "/assets/VideoGames.png",
};
